//база hfa

const hfa = [

    {
        songname: 'Button',
        artistname: 'PENGUIN RESEARCH',
        music: '1CxNufIFFDsCAW4wAUwmbpf1eTeusyA6t',
        cover: 'img/covers/button.jpg',
    },
    {
        songname: 'Ready to',
        artistname: 'Michiru Kagemori',
        music: '1ud0trWPiLItQPvPV0h1vmZecI02IfVZ6',
        cover: 'img/covers/readyto.jpg',
    },
    {
        songname: 'セイシュンゼミナール',
        artistname: 'Study',
        music: '1WugkZ2fHp27zM_KatooSAA7EAK2kiDYb',
        cover: 'img/covers/study.jpg',
    },
    {
        songname: 'Can now, Can now',
        artistname: 'Study',
        music: '1fTicAK57WyWOdDhlAGYUIOnhHP3h6uGE',
        cover: 'img/covers/cannow.jpg',
    },
    {
        songname: 'Houkagono Liberty',
        artistname: 'halca',
        music: '1eo8yklYMcGBGdF_uNUJ3RiYltQYrzR8J',
        cover: 'img/covers/houkagonoliberty.jpg',
    },
    {
        songname: 'Kyoumu Densen',
        artistname: 'ALI PROJECT',
        music: '1vUrp3G_OSsVkqdJqFCOhImlY2w9haw5H',
        cover: 'img/covers/kyoumudensen.jpg',
    },
    {
        songname: 'Endless happy world',
        artistname: 'Daisuke Ono',
        music: '1sRBCMYwd53Za7Y_duE58cMYBNYzbW-27',
        cover: 'img/covers/endlesshappyworld.jpg',
    },
    {
        songname: '徒花ネクロマンシー',
        artistname: 'FranChouChou',
        music: '1l17GaA5yyMpcLpXONpYG-cTR1gwjpY-v',
        cover: 'img/covers/fran.jpg',
    },
    {
        songname: '光へ',
        artistname: 'FranChouChou',
        music: '1Nw4nemEtPjr-IKYnpZ1dnz64IXWTdaCV',
        cover: 'img/covers/hikarie.jpg',
    },
    {
        songname: 'Kago no Naka ni Tori',
        artistname: 'yourness',
        music: '1Z5arX7kys-yGUrezEjzmK-2mDNKkwhWA',
        cover: 'img/covers/kagononakanitori.jpg',
    },
    {
        songname: 'Aoibridge',
        artistname: 'Sayuri',
        music: '1cWYnuqFGi-oUbvlO-fu8quzcp5bFS-9r',
        cover: 'img/covers/aoibridge.jpg',
    },
    {
        songname: 'イエスタディをうたって',
        artistname: 'agehasprings feat あに',
        music: '1EC2bvKXBvGvVj54cwOodpx4ZA35tFBfW',
        cover: 'img/covers/!nocover.jpg',
    },
    {
        songname: 'Zen Zen Zense (Movie Version)',
        artistname: 'RADWIMPS',
        music: '1DdyLzSzai-dGMhx7lo-LK15ztrSSUjgP',
        cover: 'img/covers/zenzenzense.jpg',
    },
    {
        songname: 'なだめスかし Negotiation',
        artistname: '鹿乃',
        music: '1KfTFlkMNlVH1uihEutLazys7PgRZp2K4',
        cover: 'img/covers/nadamesukashinegotiation.jpg',
    },
    {
        songname: 'Kokoro Knock',
        artistname: 'YuNi',
        music: '1oBdbrwHcVqGceUVEbYVGBkdpxZovSLIf',
        cover: 'img/covers/kokoroknock.jpg',
    },
    {
        songname: 'Centimeter',
        artistname: 'the peggies',
        music: '1JQiz-_YjV_P_LHkoqGB3UDq8km8opBa1',
        cover: 'img/covers/centimeter.jpg',
    },
    {
        songname: 'Kokuhaku bungee jump',
        artistname: 'halca',
        music: '1e0n1vvJ00r-ijbjIV5DRpk3dY5xiDwx8',
        cover: 'img/covers/kokuhakubungeejump.jpg',
    },
    {
        songname: 'Starting Now!',
        artistname: 'Nana Mizuki',
        music: '1PY06ZHBR03_HUDYVZ5XkKH4hn0mgl_Ft',
        cover: 'img/covers/startingnow.jpg',
    },
    {
        songname: 'Re:Re:',
        artistname: 'ASIAN KUNG-FU GENERATION',
        music: '1noDIUxkXZkXB0lIv3Abb62whSoOWvtnG',
        cover: 'img/covers/rere.jpg',
    },
    {
        songname: 'ZENRYOKU SUMMER',
        artistname: 'angela',
        music: '185KaRXdgJrOVKNZnGghD9SgfTp13DCVX',
        cover: 'img/covers/zenryokusummer.jpg',
    },
    {
        songname: '恋のうた',
        artistname: 'Yunomi',
        music: '1FS63jPRuWXn0UthPu84bHV61qM7eUEUM',
        cover: 'img/covers/yunomi.jpg',
    },
    {
        songname: 'Kiminosei',
        artistname: 'the peggies',
        music: '13eqFS1aFedCyojlcrEN3JJ2W0djG6DL0',
        cover: 'img/covers/kiminosei.jpg',
    },
    {
        songname: 'Fukashigi no Carte',
        artistname: '///',
        music: '14smfoxHPoFcxeJM474aTh9BQ9mBsBgQC',
        cover: 'img/covers/fukashiginocarte.jpg',
    },
    {
        songname: 'ココハドコ',
        artistname: 'あほむし',
        music: '1DTGLjOISgSNpYG1JCvKpC_nQLkuKqXIC',
        cover: 'img/covers/mao.jpg',
    },
    {
        songname: 'Kawakiwoameku',
        artistname: 'Minami',
        music: '1D0_qa1gN8hrT7s60QZOfetHzrFlmhLjh',
        cover: 'img/covers/kawakiwoameku.jpg',
    },
    {
        songname: 'うたたねサンシャイン',
        artistname: 'Unlimited tone',
        music: '1AEfjZrqa_-0M2d0JB7sqK0TwRV8Le3eP',
        cover: 'img/covers/unlim.jpg',
    },
    {
        songname: 'BON-BON',
        artistname: 'CooRie',
        music: '1rDwgh4G4uM9_w3oAneEYPLYTjx7xqF4-',
        cover: 'img/covers/bonbon.jpg',
    },
    {
        songname: 'Brand-new',
        artistname: 'KANA-BOON',
        music: '1cQNce-hMtvSAeI6axhsQ85XpbH1MdM7h',
        cover: 'img/covers/brandnew.jpg',
    },
    {
        songname: 'Stand by Me',
        artistname: 'the peggies',
        music: '1RZjzQf4VF8kwJPAjjXjjrRrVv5zfDA7m',
        cover: 'img/covers/standbyme.jpg',
    },
    {
        songname: 'ワガママMIRROR HEART',
        artistname: 'Ayaka Ohashi',
        music: '17g7_X5ZCAg1SPDNxotH3XA7gmvM8YYiZ',
        cover: 'img/covers/mirrorheart.jpg',
    },
    {
        songname: 'Garnet',
        artistname: 'Hanako Oku',
        music: '1W1zgVaVrhJihZWTeDooxieJUDeb0WRBu',
        cover: 'img/covers/garnet.jpg',
    },
    {
        songname: 'Fiction',
        artistname: 'sumika',
        music: '1v6L1kPLZOlMvBpNjkx-iiGk4GsmswVOR',
        cover: 'img/covers/fiction.jpg',
    },
    {
        songname: 'Kimi No Tonari',
        artistname: 'halca',
        music: '18v2A7TCay_KqENtxOYLlWN6RH6p0L5PV',
        cover: 'img/covers/kiminotonari.jpg',
    },
    {
        songname: 'SEE YOU',
        artistname: 'Yuya Matsushita',
        music: '1QBu6HtgGErR14IMf-9rLjR_Rh8iG72pq',
        cover: 'img/covers/seeyou.jpg',
    },
    {
        songname: '巣立ちの歌',
        artistname: 'アネモネリア',
        music: '1JPK9OfZ5vS8K21GXrz5rHk9DJZUrm3_t',
        cover: 'img/covers/hz1.jpg',
    },
    {
        songname: 'Life is サイダー',
        artistname: 'アネモネリア',
        music: '1lPDK20lqqbY_h2RmRJlnBt-sh71NZJst',
        cover: 'img/covers/lifeis.jpg',
    },
    {
        songname: 'お後がよろしくって・・・よ!',
        artistname: '極♨落女会',
        music: '1zSOrxbuJbqwyV_lNabwhXU9QV-iKqclC',
        cover: 'img/covers/hz2.jpg',
    },
    {
        songname: 'Nippon Egao Hyakkei',
        artistname: 'Momokurotei Ichimon',
        music: '1MfBvqVhYEHZspfRsycxDJhYH5PsK09hS',
        cover: 'img/covers/nipponegaohyakkei.jpg',
    },
    {
        songname: 'HON-NO',
        artistname: 'EMPiRE',
        music: '1C1K3KEt7tPFFJxcWt_pNzCDlF7w_6lAy',
        cover: 'img/covers/honno.jpg',
    },
    {
        songname: 'おもいでしりとり',
        artistname: 'DIALOGUE+',
        music: '1Mo4YLqU9KYOED2uGKBNg_sWT0J-0kiTF',
        cover: 'img/covers/dialogue+.jpg',
    },
    {
        songname: '大河よ共に泣いてくれ',
        artistname: 'FranChouChou',
        music: '1IJsMqFaAM7IClDX6ZTQEd8o3qMCZVlIp',
        cover: 'img/covers/fran1.jpg',
    },
    {
        songname: '夢を手に、戻れる場所もない日々を',
        artistname: 'FranChouChou',
        music: '1JDfRpiEXCUYX1DTgCPAqQs43oEL08CuZ',
        cover: 'img/covers/fran2.jpg',
    },
    {
        songname: "A Cruel Angel's Thesis",
        artistname: 'Yoko Takahashi, Shiro Sagisu',
        music: '1f-3c6hokq-p58c7zLhngI9NixMUCBg_B',
        cover: 'img/covers/acruelangelsthesis.jpg',
    },
    {
        songname: 'Komm, süsser Tod',
        artistname: 'Arianne',
        music: '1_UJOoOl5ql6C0_uR8s19QnpU0LisRBjS',
        cover: 'img/covers/kommsussertod.jpg',
    },
    {
        songname: 'Hikari No Hahen',
        artistname: 'Yu Takahashi',
        music: '1E05bHlEMAQg4tKfV4m6NgBGxqxKuJIx9',
        cover: 'img/covers/hikarinohahen.jpg',
    },
    {
        songname: 'なないろびより',
        artistname: 'nano.RIPE',
        music: '1BmIKtCX2uGUkws05GjP3f3dTzz8Tl0Ij',
        cover: 'img/covers/nr1.jpg',
    },
    {
        songname: 'こだまことだま',
        artistname: 'nano.RIPE',
        music: '1w9soqrDd-XkTvnA_c04lzcXKhK_iGG5z',
        cover: 'img/covers/nr2.jpg',
    },
    {
        songname: 'おかえり',
        artistname: '宮内れんげ、一条 蛍、越谷夏海、越谷小鞠',
        music: '1UX8VAryE78dnmQ5VOQR-LPhp37wvKbWJ',
        cover: 'img/covers/hz3.jpg',
    },
    {
        songname: 'つぎはぎもよう',
        artistname: 'nano.RIPE',
        music: '1z00UJ9MRaaLFDQaNymyR-vIrhb-X3a46',
        cover: 'img/covers/nr3.jpg',
    },
    {
        songname: 'Hikarunara',
        artistname: 'Goose house',
        music: '1oE59zhVn1nFylPGnZUbGSjdnQSQlJxkh',
        cover: 'img/covers/hikarunara.jpg',
    },
    {
        songname: 'Nanairo Symphony',
        artistname: 'COALAMODE.',
        music: '1bHuBBcMJRaPpR2ccEfdQNaCk3BgXDZAU',
        cover: 'img/covers/nanairosymphony.jpg',
    },
    {
        songname: 'Uso No Hibana',
        artistname: 'Kuroneko',
        music: '1QYi5iUhPbxsovNkNbo5q5_L-Vi_uKmUS',
        cover: 'img/covers/usonohibana.jpg',
    },
    {
        songname: 'Be Your Girl',
        artistname: '河辺千恵子',
        music: '1a1xcfGcBYxw_Fcv9vuJYAlh1GQYW1W8T',
        cover: 'img/covers/beyourgirl.jpg',
    },
    {
        songname: 'CHOIR JAIL',
        artistname: 'Konomi Suzuki',
        music: '1FfgRL0hV04mnFn4Jym3Xf6Pmh4vM9ADX',
        cover: 'img/covers/choirjail.jpg',
    },
    {
        songname: 'My Hero',
        artistname: 'MAN WITH A MISSION',
        music: '1NL1VuRw6YythrWAFTprr04O9iV1IkYzI',
        cover: 'img/covers/myhero.jpg',
    },
    {
        songname: 'ZERO!!',
        artistname: 'Minami Kuribayashi',
        music: '1Kv0kolcQn2n39yI2_sIUYEqWvmOTPKAy',
        cover: 'img/covers/zero.jpg',
    },
    {
        songname: 'Soramimi Cake',
        artistname: 'Oranges & Lemons',
        music: '19zFbUbx-BE2XZ3JbLsxneSpT6ATGUWvm',
        cover: 'img/covers/oranges&lemons.webp',
    },
    {
        songname: 'Raspberry Heaven',
        artistname: 'Oranges & Lemons',
        music: '1dn6Xq-Y6rlLkhco4UG6KY_zHZwVzENk1',
        cover: 'img/covers/oranges&lemons.webp',
    },
    {
        songname: 'プレパレード',
        artistname: '逢坂大河・櫛枝実乃梨・川嶋亜美',
        music: '1F-2t-QRUtbYFriEdGTGJSrbwxAEGkkx5',
        cover: 'img/covers/hz4.jpg',
    },
    {
        songname: 'バニラソルト',
        artistname: 'Yui Horie',
        music: '1Y-gJhStgwXiKi98l_FN7mw-VBerQHVcp',
        cover: 'img/covers/yh1.jpg',
    },
    {
        songname: 'Silky Heart',
        artistname: 'Yui Horie',
        music: '1iJPXgF19Bjrdnk9r21Obq29ZS-Xr-rL4',
        cover: 'img/covers/yh2.jpg',
    },
    {
        songname: 'オトメの心得',
        artistname: 'GARNiDELiA',
        music: '16ogddonTfGjI5vCRcfRS7sRiti0D51N2',
        cover: 'img/covers/g1.jpg',
    },
    {
        songname: 'Tenshi no Yubikiri',
        artistname: 'Fukuda Mai',
        music: '1SpIsnVPD3-HuEcwGAq6JoZ08pzKczBjZ',
        cover: 'img/covers/karekano.jpg',
    },
    {
        songname: '夢の中へ',
        artistname: 'Atsuko Enomoto, Chihiro Suzuki',
        music: '1xeNCjNXiUkMWEwX4I4p95Eam6arqHl2i',
        cover: 'img/covers/karekano.jpg',
    },
    {
        songname: 'HIGHSCHOOL OF THE DEAD',
        artistname: 'KISIDA KYODAN & THE AKEBOSI ROCKETS',
        music: '12cvqa7Pn8c-J50uURuGohTxUN1B-pwim',
        cover: 'img/covers/highschoolofthedead.jpg',
    },
    {
        songname: 'Monoqlo City',
        artistname: 'ACE COLLECTION',
        music: '1P_Acg35FdE5fGJAj1F1sr5w7vyuZLWDk',
        cover: 'img/covers/monoqlocity.jpg',
    },
    {
        songname: 'WONDERFUL WONDER',
        artistname: 'EDOGA-SULLIVAN',
        music: '1p-n_dHBzcY2zxWY_-OaRgVRvbAtKP-qt',
        cover: 'img/covers/wonderfulwonder.jpg',
    },
    {
        songname: 'Hashire Jitensha',
        artistname: 'Mishio Ogawa',
        music: '16pyugc0u7GaOHWxbhikryMmkaxRyuEfq',
        cover: 'img/covers/hashirejitensha.jpg',
    },
    {
        songname: 'サクラサク',
        artistname: 'Megumi Hayashibara',
        music: '1NXK3Nuzh4_Un1dfs2px8Zc-iM8zWI2q9',
        cover: 'img/covers/mh1.jpg',
    },
    {
        songname: '君さえいれば',
        artistname: 'Megumi Hayashibara',
        music: '1DOeNwDo3xjyIM0uJsuo3ss05eMGxeJOi',
        cover: 'img/covers/mh1.jpg',
    },
    {
        songname: 'たゆたえ、七色',
        artistname: 'ARCANA PROJECT',
        music: '1casosYFHpSQ1Yug1947TaYUzZhJIn87j',
        cover: 'img/covers/ap1.jpg',
    },
    {
        songname: 'Duvet',
        artistname: 'bôa',
        music: '12vQRzPwbK7y_-VC7jdg9ancpW8lcFa8b',
        cover: 'img/covers/duvet.jpg',
    },
    {
        songname: 'One Room Sugar Life',
        artistname: 'Nanawoakari',
        music: '1qBOMMNmWA7aCgkBaGthTILG2pz2HXl8P',
        cover: 'img/covers/oneroomsugarlife.jpg',
    },
    {
        songname: 'SWEET HURT',
        artistname: 'ReoNa',
        music: '1AdCiv8OXk1gse1qdT7roHmkqmNXAFno8',
        cover: 'img/covers/sweethurt.jpg',
    },
    {
        songname: 'パズル',
        artistname: 'ROUND TABLE feat. Nino',
        music: '1V66KHICkRBfTyoNVnC6OpHzWtXVuGgbb',
        cover: 'img/covers/pr1.jpg',
    },
    {
        songname: 'lost in the white',
        artistname: '井澤愛',
        music: '1NPNzOQYcq4sao_ZXO3raC2U8IE3FnNaq',
        cover: 'img/covers/lostinthewhite.jpg',
    },
    {
        songname: 'Dearest',
        artistname: '三重野瞳',
        music: '1Kxy-bnzUzL6TMrtQgfXLGHRoE6OKn2BH',
        cover: 'img/covers/dearest.jpg',
    },
    {
        songname: 'キラメク',
        artistname: 'yozuca*',
        music: '1nAhSJMhCSXnlhND-ExFIF0hD2zOwrpOl',
        cover: 'img/covers/yz1.jpg',
    },
    {
        songname: 'incl.',
        artistname: 'meg rock',
        music: '1sTrmsaM-mTAxo9-Cfz_d2fpwX-ztsaDt',
        cover: 'img/covers/incl.jpg',
    },
    {
        songname: 'Changing point',
        artistname: 'i☆Ris',
        music: '1zpE5KUthUYVeB9aoSKGxMFMGPNSz4EBq',
        cover: 'img/covers/changingpoint.jpg',
    },

    //беда
    {
        songname: 'おかえり',
        artistname: '宮内れんげ、一条 蛍、越谷夏海、越谷小鞠',
        music: '1UX8VAryE78dnmQ5VOQR-LPhp37wvKbWJ',
        cover: 'img/covers/hz3.jpg',
    },
    {
        songname: 'Fukashigi no Carte',
        artistname: '桜島麻衣、古賀朋絵、双葉理央、豊浜のどか、梓川かえで、牧之原翔子',
        music: '1WrgTzMbrt8OLWqWrNiOB7Frq9_I-xNPf',
        cover: 'img/covers/fukashiginocarte.jpg',
    },
    {
        songname: 'プレパレード',
        artistname: '逢坂大河・櫛枝実乃梨・川嶋亜美(釘宮理恵、堀江由衣、喜多村英梨)',
        music: '1F-2t-QRUtbYFriEdGTGJSrbwxAEGkkx5',
        cover: 'img/covers/hz4.jpg',
    },
    //конец беды

    {
        songname: 'x',
        artistname: 'x',
        music: 'x',
        cover: 'img/covers/x.jpg',
    },
    {
        songname: 'x',
        artistname: 'x',
        music: 'x',
        cover: 'img/covers/x.jpg',
    },
    {
        songname: 'x',
        artistname: 'x',
        music: 'x',
        cover: 'img/covers/x.jpg',
    },
];

let trackindex = 79;

const def = 79;



